# Module to merge preflag plots

import os
import numpy as np
#import pymp
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import socket
import glob


def combine_preflag_plots(qa_dir, trigger_mode=False):
    """
    Function to combine the plots generated by preflag

    """

    print("Combining preflag plots")

    # General set up
    # ==============

    # set the list of preflag directories to search
    default_path = os.path.join(qa_dir, "preflag")
    if socket.gethostname() != 'happili-01' or trigger_mode:
        qa_preflag_dir_list = [default_path]
    else:
        qa_preflag_dir_list = [default_path, default_path.replace(
            "data", "data2"), default_path.replace("data", "data3"), default_path.replace("data", "data4")]

    # get a list of beam directories
    qa_preflag_beam_dir_list = np.array([
        glob.glob(os.path.join(preflag_dir, "[0-3][0-9]")) for preflag_dir in qa_preflag_dir_list])

    # combine the beam directory arrays arrays
    qa_preflag_beam_dir_list = np.concatenate(qa_preflag_beam_dir_list)

    if len(qa_preflag_beam_dir_list) == 0:
        print("No beam directories found")
        return -1
    else:
        qa_preflag_beam_dir_list.sort()

    # get a list of beams
    beam_list = np.array([os.path.basename(beam_dir)
                          for beam_dir in qa_preflag_beam_dir_list])

    print(beam_list)

    # get a list of pngs:
    qa_preflag_beam_png_list = np.array([glob.glob(os.path.join(
        beam_dir, "*.png")) for beam_dir in qa_preflag_beam_dir_list])

    # combine the list
    qa_preflag_beam_png_list = np.concatenate(qa_preflag_beam_png_list)

    if len(qa_preflag_beam_png_list) == 0:
        print("No images found")
        return -1
    else:
        qa_preflag_beam_png_list.sort()

    # get a list of unique png names
    png_name_full_list = np.array([os.path.basename(png_name)
                                   for png_name in qa_preflag_beam_png_list])

    png_name_unique_list = np.unique(png_name_full_list)

    print("Following plots were found {}".format(str(png_name_unique_list)))

    # Going through the different pngs and combine them
    # =================================================

    for png_name in png_name_unique_list:

        # get the source name
        src_name = png_name.split("_")[0]

        # name of new image
        output_image_name = os.path.join(
            default_path, png_name.replace(".png", "_combined.png"))

        print("Creating {}".format(output_image_name))

        # get a list of indices which correspond to this png
        png_indices = np.where(png_name_full_list == png_name)[0]

        # number of pngs
        n_png = np.size(png_indices)

        # get a list of png files for the given type of png
        png_path_list = qa_preflag_beam_png_list[png_indices]

        # get a list of beams for this type of png
        beam_png_list = np.array(
            [os.path.basename(os.path.dirname(png_path)) for png_path in png_path_list])

        print(beam_png_list)

        # setting up the plot
        nx = 8
        ny = 5
        xsize = nx*4
        ysize = ny*4
        #fig, axes = plt.subplots(4, 10, figsize=(xsize, ysize))
        plt.figure(figsize=(xsize, ysize))
        plt.suptitle(
            '{0}'.format(png_name.split(".png")[0]), size=30)

        # go through the list of png
        for k in range(n_png):
            beam_nr = int(beam_png_list[k])
            x_pos = beam_nr % 4
            y_pos = beam_nr % 10
            ax = plt.subplot(nx, ny, int(beam_png_list[k])+1)
            plt_img = plt.imread(png_path_list[k])
            ax.imshow(plt_img)
            plt.title('{0}'.format(beam_nr))
            #axes[x_pos, y_pos].imshow(plt_img)
            ax.axis('tight')
            ax.axis('off')
            ax.set_aspect("equal")

        #plt.subplots_adjust(left=0.0, right=1.0, bottom=0.0, top=1.0)
        plt.subplots_adjust(wspace=-0.8, hspace=0.4)
        plt.savefig(output_image_name, overwrite=True,
                    bbox_inches='tight', dpi=200)
        plt.close("all")


# for debugging
if __name__ == "__main__":
    path = "/data/apertif/190602049_flag-strategy-test/qa"
    combine_preflag_plots(path)
